### ISSUE TITLE
Games do not launch when clicking on play

### ISSUE THREAD

**Issue by DoyesBoyes** [j-selby/galaxy-integration-citra#1]
When I try to launch a 3DS game via GOG Galaxy 2.0, it doesn't open Citra to launch it. I'm not sure if that's the intent of this plug in, but seeing as Citra nightly is required I assumed that's the case.

**Comment by NoShotz** [comment]
It's likely due to you needing to use the installer for citra, and have it install to the default location, really you should just be able to set your own directory for the exe in the plugin like you set the games path.

**Comment by DoyesBoyes** [comment]
Tried changing the path but it did not seem to work

**Comment by LeonardFiedrowicz** [comment]
You could upload the log found at 
"C:\ProgramData\GOG.com\Galaxy\logs\plugin-3ds-c6596e5a-5f3a-4681-942a-746433f255ff.log"

**Comment by DoyesBoyes** [comment]
[plugin-3ds-c6596e5a-5f3a-4681-942a-746433f255ff.log](https://github.com/j-selby/galaxy-integration-citra/files/3667717/plugin-3ds-c6596e5a-5f3a-4681-942a-746433f255ff.log)

Apologies for the hiatus, here are the logs @LeonardFiedrowicz

**Comment by LeonardFiedrowicz** [comment]
It seems like the plugin either couldn't find citra or the game.
Maybe check if you set that citra path correctly.

I made a pull request where you can set the citra folder when doing the integration for the first time. Maybe give that a try.
https://github.com/LeonardFiedrowicz/galaxy-integration-citra
Replacing the plugin.py should be enough.

**Comment by DoyesBoyes** [comment]
@LeonardFiedrowicz used your new plugin.py and that sorted out my problem with ease. Very much appreciated. I'll close out this issue.
